import type { LearningProposal, LearningProposalSet } from "../../learning-governance/src/index.js";
import type { LearningCostOpportunity, LearningFailurePattern, LearningRouteFeedbackSummary } from "../../learning-evidence/src/index.js";

export { writeLearningProposalFiles, type LearningProposalFileSet } from "./storage.js";

export type LearningProposalEvidence = { projectDir: string; generatedAt: string; runsAnalyzed: number; evaluationRuns: number; repeatedFailurePatterns: LearningFailurePattern[]; costOpportunities: LearningCostOpportunity[]; routeFeedback: LearningRouteFeedbackSummary; evalGaps: string[]; proposalPreview: { total: number; highPriority: number; byKind: Record<string, number> } };
const counts = (values: string[]) => values.reduce<Record<string, number>>((out, value) => { out[value] = (out[value] ?? 0) + 1; return out; }, {});
const add = (items: LearningProposal[], proposal: Omit<LearningProposal, "id">) => items.push({ ...proposal, id: `learn-${String(items.length + 1).padStart(3, "0")}` });

export function buildLearningProposalSet(report: LearningProposalEvidence): LearningProposalSet {
  const proposals: LearningProposal[] = [];
  for (const p of report.repeatedFailurePatterns.slice(0, 5)) add(proposals, { priority: p.failureRate >= .5 ? "high" : "medium", kind: "repeated_failure", riskLevel: "high", title: `Investigate repeated failures in ${p.stageId}`, target: `${p.workflowId}/${p.stageId}/${p.agentId}`, rationale: `${p.failedTasks} of ${p.totalTasks} recent stage task(s) failed.`, evidence: [`workflow=${p.workflowId}`, `stage=${p.stageId}`, `agent=${p.agentId}`, `failureRate=${p.failureRate}`], recommendation: "Queue a debug-failure run or add targeted eval coverage before changing workflow behavior.", approvalRequired: true });
  for (const p of report.costOpportunities.slice(0, 5)) add(proposals, { priority: p.fallbackRate >= .5 ? "high" : "medium", kind: "cost_routing", riskLevel: "medium", title: `Review routing for ${p.stageId}`, target: `${p.workflowId}/${p.stageId}/${p.agentId}`, rationale: `Route ${p.providerId}/${p.modelTier} has fallback=${p.fallbackRate}, latency=${p.averageLatencyMs ?? "n/a"}ms, runs=${p.runs}.`, evidence: [`provider=${p.providerId}`, `modelTier=${p.modelTier}`, `fallbackRate=${p.fallbackRate}`, `averageLatencyMs=${p.averageLatencyMs ?? "n/a"}`], recommendation: `${p.recommendation} In autonomous mode, write project-local tuning overlay notes before promoting any shared workflow or provider change.`, approvalRequired: false });
  const routeProposal = (group: LearningRouteFeedbackSummary["costlyGroups"][number], helpful: boolean): Omit<LearningProposal, "id"> => ({ priority: (helpful ? group.helpful : group.costly) >= 2 ? "medium" : "low", kind: "route_feedback", riskLevel: "low", title: `${helpful ? "Preserve helpful" : "Review costly"} route feedback for ${group.target.split("/")[1] ?? group.target}`, target: group.target, rationale: `${helpful ? group.helpful : group.costly} ${helpful ? "helpful" : "costly"} route feedback signal(s) were recorded for ${group.route} (${group.routeClass}).`, evidence: [`route=${group.route}`, `routeClass=${group.routeClass}`, `helpful=${group.helpful}`, `costly=${group.costly}`, `neutral=${group.neutral}`, `latest=${group.latestAt ?? "n/a"}`], recommendation: helpful ? "Refresh savings-aware local routing recommendations so repeated helpful signals can strengthen low-risk local routing trial candidates without changing provider defaults directly." : "Refresh savings-aware local routing recommendations and prepare a project-local routing-note plan if the evidence still supports retreating, holding, or expanding this route.", approvalRequired: false });
  for (const group of report.routeFeedback.costlyGroups.slice(0, 5)) add(proposals, routeProposal(group, false));
  for (const group of report.routeFeedback.helpfulGroups.slice(0, 3)) add(proposals, routeProposal(group, true));
  for (const gap of report.evalGaps) { const feedback = gap.toLowerCase().includes("feedback"); add(proposals, { priority: feedback ? "medium" : "low", kind: feedback ? "feedback_gap" : "eval_gap", riskLevel: feedback ? "low" : "high", title: feedback ? "Collect developer feedback" : "Improve evaluation evidence", target: report.projectDir, rationale: gap, evidence: [`runsAnalyzed=${report.runsAnalyzed}`, `evaluationRuns=${report.evaluationRuns}`], recommendation: feedback ? "Record accepted, revised, or rejected feedback on recent workflow runs before promoting tuning changes." : "Create or run a small local evaluation suite before applying prompt, routing, or context-budget changes.", approvalRequired: !feedback }); }
  if (report.proposalPreview.total) add(proposals, { priority: report.proposalPreview.highPriority ? "high" : "medium", kind: "proposal_followup", riskLevel: "medium", title: "Review tuning proposal candidates", target: report.projectDir, rationale: `${report.proposalPreview.total} tuning proposal candidate(s), including ${report.proposalPreview.highPriority} high-priority item(s), are available.`, evidence: Object.entries(report.proposalPreview.byKind).map(([kind, count]) => `${kind}=${count}`), recommendation: "Write project-local tuning overlay notes automatically in autonomous mode. Promote shared workflow/provider changes only with approval.", approvalRequired: false });
  const kinds = counts(proposals.map((proposal) => proposal.kind));
  const summary = proposals.length ? [`${proposals.length} proposal candidate(s) from ${report.runsAnalyzed} run(s).`, `${proposals.filter((proposal) => proposal.priority === "high").length} high-priority proposal(s).`, `${proposals.filter((proposal) => proposal.approvalRequired).length} proposal(s) require approval before any behavior-changing action.`, `Kinds: ${Object.entries(kinds).map(([key, value]) => `${key}=${value}`).join(", ") || "none"}.`] : ["No learning proposal candidates were found in the inspected run window."];
  return { kind: "agentflow_learning_proposals", projectRootUri: report.projectDir, generatedAt: new Date().toISOString(), sourceReportGeneratedAt: report.generatedAt, sourceRunsAnalyzed: report.runsAnalyzed, proposals, summary };
}

export function formatLearningProposalSet(set: LearningProposalSet): string { return [`Learning Proposals: ${set.projectRootUri}`, `Generated: ${set.generatedAt}`, `Runs analyzed: ${set.sourceRunsAnalyzed}`, "", "Summary", ...set.summary.map((item) => `- ${item}`), "", "Proposals", ...(set.proposals.length ? set.proposals.map((p) => `- ${p.id} [${p.priority}] ${p.kind}: ${p.title}\n  - Target: ${p.target}\n  - Risk: ${p.riskLevel}${p.approvalRequired ? " approval-required" : " report-only"}\n  - Rationale: ${p.rationale}\n  - Recommendation: ${p.recommendation}`) : ["- No learning proposals yet."])].join("\n"); }
export function formatLearningProposalMarkdown(set: LearningProposalSet): string { return ["# Agent Workflow Learning Proposals", "", `Project: ${set.projectRootUri}`, `Generated: ${set.generatedAt}`, `Source report: ${set.sourceReportGeneratedAt}`, `Source runs analyzed: ${set.sourceRunsAnalyzed}`, "", "## Summary", "", ...set.summary.map((item) => `- ${item}`), "", ...set.proposals.map((p) => `## ${p.id} - ${p.title}\n\n- Priority: ${p.priority}\n- Kind: ${p.kind}\n- Risk: ${p.riskLevel}\n- Target: ${p.target}\n- Approval required: ${p.approvalRequired ? "yes" : "no"}\n- Rationale: ${p.rationale}\n- Recommendation: ${p.recommendation}\n\nEvidence:\n${p.evidence.map((item) => `- ${item}`).join("\n")}\n`)].join("\n"); }
